"""Ollama APIのHTTP呼び出し、共有セッション、JSON応答検証、生成文クリーニングAPIを提供する。"""
from __future__ import annotations

import logging

from ..ollama_reply_safety import (
    _PROMPT_LEAK_PATTERNS,
    _REASONING_LEAK_PATTERNS,
    _extract_labeled_user_facing_line,
    _is_compliance_or_acceptance_clause,
    _looks_like_analysis_label,
    _looks_like_conversational_reply_excerpt,
    _looks_like_control_line,
    _looks_like_duplicate_think_echo,
    _looks_like_fragmentary_meta_summary,
    _looks_like_labeled_analysis_line,
    _looks_like_opening_topic_echo,
    _looks_like_pre_think_leak,
    _looks_like_structured_analysis_block,
    _normalize_compare_text,
    _normalize_topic_echo_text,
    _opening_echo_fragment,
    _strip_leading_list_marker,
    _strip_leading_non_user_facing_paragraph,
    _strip_think_blocks,
    extract_effective_first_clause,
    extract_first_user_facing_reply,
    strip_leading_interjections,
    looks_like_abnormal_assistant_reply,
    looks_like_multi_turn_output,
    looks_like_non_japanese_reply,
    looks_like_parrot_reply,
    looks_like_prompt_leak,
    looks_like_reasoning_leak,
    looks_like_similar_to_previous_reply,
    _looks_too_similar_to_previous_reply,
    looks_like_truncated_reply,
    looks_like_unusable_assistant_reply,
    looks_like_time_of_day_contradiction,
    looks_like_character_deviation,
    salvage_reply_from_think_block,
    sanitize_generated_reply,
    strip_markdown_artifacts,
    strip_unprompted_nerd_emoji,
)

from .client import (
    OllamaChatResult,
    OllamaImageNotSupportedError,
    OllamaJSONInvalidError,
    OllamaJSONTruncatedError,
    OllamaThinkingNotSupportedError,
    _build_options,
    _build_timeout,
    _bump_num_predict,
    _cfg,
    _cfg_float_value,
    _cfg_int_value,
    _get_ollama_request_semaphore,
    _get_ollama_session,
    _is_bad_request_http_error,
    _is_ollama_busy_error,
    _is_retryable_http_error,
    _merge_generation_kwargs_into_options,
    _ollama_request_semaphore,
    _ollama_request_semaphore_limit,
    _reset_ollama_session,
    _resolve_keep_alive,
    _retry_sleep_seconds,
    _shared_ollama_session,
    _shared_ollama_session_lock,
    _should_reset_ollama_session_for_error,
    _should_retry_length_limited_chat,
    _should_send_think_flag,
    close_ollama_session,
    release_ollama_model,
)

from .text import (
    _log_ollama_payload,
    _looks_like_think_only_output,
    _mask_text_for_log,
    truncate_lines,
    truncate_text,
)

from .chat import (
    _post_chat_once,
    call_ollama,
    call_ollama_chat_raw,
)

from .embeddings import (
    call_ollama_batch_embeddings,
    call_ollama_embeddings,
)

from .structured import (
    _json_schema_type_matches,
    _looks_like_truncated_json_text,
    _validate_json_schema_subset,
    call_ollama_json,
)

log = logging.getLogger("ollama_bot.common.ollama")

__all__ = [
    # ollama_reply_safety re-exports
    "_PROMPT_LEAK_PATTERNS",
    "_REASONING_LEAK_PATTERNS",
    "_extract_labeled_user_facing_line",
    "_is_compliance_or_acceptance_clause",
    "_looks_like_analysis_label",
    "_looks_like_conversational_reply_excerpt",
    "_looks_like_control_line",
    "_looks_like_duplicate_think_echo",
    "_looks_like_fragmentary_meta_summary",
    "_looks_like_labeled_analysis_line",
    "_looks_like_opening_topic_echo",
    "_looks_like_pre_think_leak",
    "_looks_like_structured_analysis_block",
    "_normalize_compare_text",
    "_normalize_topic_echo_text",
    "_opening_echo_fragment",
    "_strip_leading_list_marker",
    "_strip_leading_non_user_facing_paragraph",
    "_strip_think_blocks",
    "extract_effective_first_clause",
    "extract_first_user_facing_reply",
    "looks_like_abnormal_assistant_reply",
    "looks_like_multi_turn_output",
    "looks_like_non_japanese_reply",
    "looks_like_parrot_reply",
    "looks_like_prompt_leak",
    "looks_like_reasoning_leak",
    "looks_like_similar_to_previous_reply",
    "_looks_too_similar_to_previous_reply",
    "looks_like_truncated_reply",
    "looks_like_unusable_assistant_reply",
    "looks_like_time_of_day_contradiction",
    "looks_like_character_deviation",
    "salvage_reply_from_think_block",
    "sanitize_generated_reply",
    "strip_leading_interjections",
    "strip_markdown_artifacts",
    "strip_unprompted_nerd_emoji",
    # client
    "OllamaChatResult",
    "OllamaImageNotSupportedError",
    "OllamaJSONInvalidError",
    "OllamaJSONTruncatedError",
    "OllamaThinkingNotSupportedError",
    "_build_options",
    "_build_timeout",
    "_bump_num_predict",
    "_cfg",
    "_cfg_float_value",
    "_cfg_int_value",
    "_get_ollama_request_semaphore",
    "_get_ollama_session",
    "_is_bad_request_http_error",
    "_is_ollama_busy_error",
    "_is_retryable_http_error",
    "_merge_generation_kwargs_into_options",
    "_ollama_request_semaphore",
    "_ollama_request_semaphore_limit",
    "_reset_ollama_session",
    "_resolve_keep_alive",
    "_retry_sleep_seconds",
    "_shared_ollama_session",
    "_shared_ollama_session_lock",
    "_should_reset_ollama_session_for_error",
    "_should_retry_length_limited_chat",
    "_should_send_think_flag",
    "close_ollama_session",
    "release_ollama_model",
    # text
    "_log_ollama_payload",
    "_looks_like_think_only_output",
    "_mask_text_for_log",
    "truncate_lines",
    "truncate_text",
    # chat
    "_post_chat_once",
    "call_ollama",
    "call_ollama_chat_raw",
    # embeddings
    "call_ollama_batch_embeddings",
    "call_ollama_embeddings",
    # structured
    "_json_schema_type_matches",
    "_looks_like_truncated_json_text",
    "_validate_json_schema_subset",
    "call_ollama_json",
]
