"""LLM生成文における内部指示漏れおよび思考漏洩の検出正規表現パターン定義。"""
from __future__ import annotations

import re

_PROMPT_LEAK_PATTERNS: tuple[str, ...] = (
    r"システムプロンプト",
    r"system prompt",
    r"developer message",
    r"内部指示",
    r"上記のルール",
    r"以下のルールに従",
    r"(?:この)?ルール(?:は|を|が)?(?:絶対|厳守|遵守|守る|まもる)",
    r"ルール(?:は|が)?絶対",
    r"指示(?:を|に)?(?:絶対|厳守|遵守|従い|従う|守る)",
    r"指示通りに(?:返答|作成|生成|出力|会話)",
    r"上記の(?:指示|ルール|設定|条件)",
    r"以下の(?:指示|ルール|設定|条件)",
    r"絶対厳守",
    r"外部調査の指示",
    r"外部調査結果",
    r"最終優先指示",
    r"対象メッセージ",
    r"対象の発言",
    r"対象文章",
    r"指示[:：]",
    r"調査理由[:：]",
    r"検索クエリ[:：]",
    r"検索結果[:：]",
    r"URL解決結果",
    r"返答本文だけ",
    r"絶対に[^。\n]{0,80}(?:AI|bot|ボット)[^。\n]{0,80}(?:使わない|出さない|出力しない|書かない|言わない|含めない)こと(?:[。.!！]|$)",
    r"(?:AI|bot|ボット)[^。\n]{0,80}(?:言葉|単語|表現)[^。\n]{0,80}(?:使わない|出さない|出力しない|書かない|言わない|含めない)こと(?:[。.!！]|$)",
    r"キャラクター設定.*口調",
    r"観測した投稿本文.*説明してください",
    r"本文に現れた話題.*返答の中心",
    r"今観測した投稿.*ただ列挙",
    r"取れた投稿.*ただ列挙",
    r"全体の傾向.*複数投稿の共通点.*目立った個別例",
    r"直近で気になっている題材",
    r"最近気になっている題材",
    r"内部素材",
    r"^\s*(?:[-*・]\s*)?(?:相手の意図|ユーザーの最新発言|最新のユーザー発言|最新の相手の発言|会話の背景|返答スタイル|応答スタイル)[:：]",
    r"返答前の内省メモ",
    r"内省メモ[:：]",
    r"※?内省メモ(?:はここまで|終了|の整理)?",
    r"これらを踏まえて[、，]?",
    r"\[/?(?:返答前の)?内省メモ\]",
    r"【/?(?:返答前の)?内省メモ】",
    r"キャラ維持指示[:：]",
    r"感情の軸[:：]",
    r"拾う記憶[:：]",
    r"返答方針[:：]",
    r"避けること[:：]",
    r"熟考トリガー[:：]",
    r"（あなたへの返信）",
    r"（.+の「.+」への返信）",
    r"直前の(?:AI|自分の)発言[:：]",
    r"会話履歴[:：]",
    r"【返答の形式】",
    r"【キャラクター設定】",
    r"【この相手との関係性】",
    r"【過去の話題の引き継ぎ禁止】",
    r"感情表現の指針",
    r"感情を説明しすぎず",
    r"会話の自然さを優先",
    r"主語はAI側に置いたまま",
    r"引き受けるか断るかの形",
    r"相手が言っていない理由や背景",
    r"勝手に補完・推測して",
    r"断定・同調しないでください",
    r"直前の自分の発言・スタンスに固執せず",
    r"自分の誤解を素直に認めて",
    r"取り乱さないでください",
    r"短く返してください",
    r"曲解して",
    r"振れすぎないでください",
    r"反映してください",
    r"優先してください",
    r"使ってください",
    r"答えてください",
    r"(?:しないで|避けて|保って|認めて|捨てて|広げて|返して|書いて|置いて|述べて)ください[。.]?$",
    r"^\s*(?:[-*・]\s*)?(?:何に対してどう返すか|何かを教える必要があるか|相手の言葉の裏の意味)[:：]",
    r"^\s*(?:[-*・]\s*)?(?:本題|要点|結論|返答の狙い|返答方針|回答方針|話題|文脈|状況整理)[:：]",
    r"^\s*(?:[-*・]\s*)?.{0,48}(?:受け止め方|直接的な回答|返答の方向|回答の方向|切り抜ける方向|相手への返し)[:：]",
    r"\d+\s*[〜~～-]\s*\d+\s*文.*文字程度",
    r"^\s*(?:[-*・]\s*)?(?:返答の温度感|相手への態度|返答の長さ|相手の発言に対するリアクション|感情表現の指針|リアクション)[:：]",
    r"^\s*(?:[-*・]\s*)?(?:感情|関係性|親密度|信頼度|感情状態|警戒心|冷淡さ|相手の発言分析|ユーザー発言分析|発言分析|禁止事項|内省|自己内省|感情調整|口調調整|返答戦略|口調)[:：]",
    r"^\s*(?:[-*・]\s*)?返答\s*$",
    r"【指示】",
    r"【対象文章】",
    r"【対象の発言】",
    r"【検索結果】",
    r"【検索クエリ】",
    r"思考プロセスや(?:思考タグ|thinkタグ|<think>タグ|タグ)",
    r"返答本文だけを(?:1〜2文で)?直接出力",
    r"あなたのキャラクター（Assistant）としての自然な日本語",
    r"私じゃなくて[、，\s]*.+さんのこと",
    r"(?:あなた|AI)に向けられた発言ではない",
    r"ユーザー同士のやり取り",
    r"状況のメタ説明",
    r"外野から自然に相槌",
    r"avoids?\s+[\"“「]",
    r"uses?\s+[\"“「]",
    r"Maintain the character",
    r"Analyze User Input",
    r"Deconstruct Persona",
    r"Persona Constraints",
    r"Key Rules",
    r"Core Task",
    r"Recent Tweets",
    r"suffix stacking",
    r"unnatural suffix",
    r"Output ONLY the dialogue",
    r"slightly nerdy",
    r"no unnatural",
    r"直近投稿の空気感",
    r"話題の偏り",
    r"温度感を踏まえて",
    r"Discordの流れを壊さない",
    r"短い話題振りを(?:一つ|1つ)だけ(?:自然に)?(?:出せ|出して)",
    r"話題振りを(?:一つ|1つ)だけ(?:自然に)?(?:出せ|出して)",
    r"スレッド一覧から.*(?:短い)?話題振りを",
    r"ユーザー関心事を材料にして",
    r"一時的な話題として扱い",
    r"宣伝句や肩書きは.*話題として扱わない",
    r"話題判断は本文を最優先",
    r"ツイート本文の丸写し",
    r"本文の丸写しや、各スレッドの列挙は禁止",
    r"材料にして.*自然な話題振りを",
    r"自然な1つの発言をして",
    r"誰でも乗りやすい内容",
    r"自然で短い話題を1つ",
)

_REASONING_LEAK_PATTERNS: tuple[str, ...] = (
    r"^思考[:：]",
    r"^推論[:：]",
    r"^reasoning[:：]",
    r"^chain of thought",
    r"^thinking process[:：]",
    r"<think>",
    r"</think>",
    r"<thought>",
    r"</thought>",
    r"^\s*\[(?:返答前の)?内省メモ\]",
    r"^\s*【(?:返答前の)?内省メモ】",
    r"^\s*【(?:思考|推論|内省|整理|考察)】",
    r"^\s*\[(?:思考|推論|内省|整理|考察)\]",
    r"^\s*(?:思考|推論|整理|考察)の?メモ[:：]",
    r"^\s*(?:I'll|Let's|Here's|Wait|Actually|The prompt|Self-Correction|Check|Drafting|Note[:：]|Refinement|Output matches|Final check|Analyze|Deconstruct|Persona|Maintain|Core Task|Recent Tweets)\b",
    r"\(Matches(?:\s+exactly)?\)",
    r"\bMatches\s+exactly\b",
    r"\bOutput matches\b",
    r"\bproceeds\b",
    r"\(verified\)",
    r"\(passed\)",
    r"\bSelf-Correction\b",
    r"\[(?:Output\s+Generation|Final\s+Output|Output)\]",
)


def looks_like_prompt_leak(text: str) -> bool:
    """プロンプト指示文の断片や内部メタ情報が漏洩していないか検証する。"""
    t = str(text or "")
    return any(re.search(p, t, flags=re.IGNORECASE | re.MULTILINE) for p in _PROMPT_LEAK_PATTERNS)


def looks_like_reasoning_leak(text: str) -> bool:
    """推論プロセスのキーワードや思考タグが漏洩していないか検証する。"""
    t = str(text or "")
    return any(re.search(p, t, flags=re.IGNORECASE | re.MULTILINE) for p in _REASONING_LEAK_PATTERNS)


def looks_like_multi_turn_output(text: str) -> bool:
    """user/assistant/system などのマルチターン出力が混入していないか判定する。"""
    t = str(text or "")
    markers = len(re.findall(r"^(?:user|assistant|system)\s*[:：]", t, flags=re.IGNORECASE | re.MULTILINE))
    return markers >= 2
